// 癌症登記長表欄位代碼。與 QBC 的 qbc-field 同一個用途：
// 保存來源欄位代號，不取代國健署公布之申報規格。

CodeSystem: TCRFieldCodeSystem
Id: tcr-field
Title: "TCR Longform Field Codes"
Description: "非官方台灣癌症登記長表欄位代碼彙整。"
* ^status = #draft
* ^experimental = true
* ^caseSensitive = true
* ^content = #complete
* #PK "病歷號／個案識別碼"
* #SEX "性別"
* #AGE "診斷時年齡"
* #DX_YEAR "診斷年"
* #DXDATE "診斷日期"
* #VISTDATE "首次就診日期"
* #SMOKING "吸菸／檳榔／飲酒"
* #HEIGHT "身高"
* #WEIGHT "體重"
* #KPSECOG "體能狀態 ECOG/KPS"
* #CLASS95 "個案分類"
* #CLASSOFDIAG "診斷分類（本院／他院）"
* #CLASSOFTREAT "治療分類（本院／他院）"
* #SEQ1 "腫瘤總數"
* #SEQ2 "本腫瘤序號"
* #TCODE1 "原發部位 ICD-O-3"
* #LAT95 "側性"
* #MCODE "組織型態 ICD-O-3"
* #MCODE5 "行為碼"
* #MCODE6 "病理分化度"
* #MCODE6C "臨床分化度"
* #CONFER "診斷確認方式"
* #CSIZE95 "腫瘤大小 (mm)"
* #PNI "神經周圍侵犯"
* #LVI "淋巴血管侵犯"
* #LNEXAM "區域淋巴結檢查數"
* #LN_POSITI "區域淋巴結侵犯數"
* #AJCC "AJCC 版本"
* #CT "臨床 T"
* #CN "臨床 N"
* #CM "臨床 M"
* #CSTG "臨床期別"
* #PT "病理 T"
* #PN "病理 N"
* #PM "病理 M"
* #PSTG "病理期別"
* #SUMSTG "合併期別"
* #OSTG "其他分期系統"
* #OCSTG "其他系統臨床期別"
* #OPSTG "其他系統病理期別"
* #META1 "遠端轉移部位 1"
* #META2 "遠端轉移部位 2"
* #META3 "遠端轉移部位 3"
* #S "本院手術"
* #FSDATE "首次手術日期"
* #PRESTYPE "他院手術方式"
* #STYPE95 "本院手術方式"
* #MINS "微創手術"
* #MARG95 "手術切緣狀態"
* #MARGDIS "手術切緣距離 (mm)"
* #PRESLNSCO "他院區域淋巴結手術"
* #SLNSCO95 "本院區域淋巴結手術"
* #SSF1 "SSF1 動情激素接受體 ER"
* #SSF2 "SSF2 黃體激素接受體 PR"
* #SSF3 "SSF3 前導性療法之療效"
* #SSF4 "SSF4 哨兵淋巴結檢查數目"
* #SSF5 "SSF5 哨兵淋巴結侵犯數目"
* #SSF6 "SSF6 Nottingham/BR 分數與級數"
* #SSF7 "SSF7 HER2 IHC/ISH"
* #SSF8 "SSF8 Paget 氏症"
* #SSF9 "SSF9 淋巴管或血管侵犯"
* #SSF10 "SSF10 Ki-67"
* #R "本院放射治療"
* #RTAR "放療標的總結"
* #RMOD "放療方式"
* #EBRT "體外放射治療技術"
* #HTAR "高劑量標的"
* #HDOSE "高劑量劑量 (cGy)"
* #HNO "高劑量分次數"
* #LTAR "低劑量標的"
* #LDOSE "低劑量劑量 (cGy)"
* #LNO "低劑量分次數"
* #SEQRS "放療與手術順序"
* #SEQLS "局部與全身治療順序"
* #PREC "他院化學治療"
* #C "本院化學治療"
* #PREH "他院荷爾蒙治療"
* #H "本院荷爾蒙治療"
* #PREI "他院免疫治療"
* #I "本院免疫治療"
* #PREB "他院骨髓／幹細胞移植"
* #B "本院骨髓／幹細胞移植"
* #PRETAR "他院標靶治療"
* #TAR "本院標靶治療"
* #OTH "其他治療"
* #PREP "安寧緩和照護"
* #WATCHWAITING "積極監測"
* #VSTA "生命狀態（首次追蹤）"
* #CSTA "癌症狀態（首次追蹤）"
* #LCD "最後接觸日期"
* #REDATE "復發日期"
* #RETYPE95 "復發型態"
* #DIECAUSE "死亡原因"
* #VSTA6 "生命狀態（延長追蹤）"
* #LCD6 "最後接觸日期（延長追蹤）"
* #SURVY6 "存活年數"
* #REDATE6 "復發日期（延長追蹤）"
* #RETYPE6 "復發型態（延長追蹤）"
* #DIECAUSE6 "死亡原因（延長追蹤）"
